### ISSUE TITLE
blog next, previous buttons

### ISSUE THREAD

**Issue by berlintam** [rubycorns/rorganize.it#232]
It would be cool to have `next` and `previous` buttons on each posts#show page so that our eager readers can easily manoeuvre from one blogpost to the next.

**Comment by mariemariemarie** [comment]
we discovered, there is already pagination in the code in the post controller.
It is currently 20 posts/page, we are going to reduce this to 5.
currently there are no tests for this, we will write one.

**Comment by berlintam** [comment]
I was thinking about this again since last night, and I think this issue was more meant as having next, previous buttons on the posts show pages. 

A post show page is this: http://rorganize.it/posts/we-heart-emojis
As opposed to the index page, which is this http://rorganize.it/posts

So someone can click on an individual post, and then hit next, and go to the next one, or back, and go back one. 

I think that the pagination that's already there is just for the index page.

Anyway, sorry for the confusion! and yay tests :)

**Comment by sareg0** [comment]
There has been some complications with this, and I need to do two thing in order to finish fixing

- I am considering turning the published_on column into a datetime object. Currently we are sorting by created_at. This doesn't work, as the blog post may have been created_at a certain time and stored as a draft for sixmonths... So it messes up the order. I want to order by published_on, but if there are multiple posts published on that date, then we need to sort by time of the publishing. I am not sure about the implications of this
- I have discovered that the blog is mistaking 'drafts' as something that should be listed, at least locally. It doesn't seem to be that case in production Because of the 'show_date' method in the helpers. It's using saying that if there is no published on date one should show 'draft created at  on'... It's a bit misleading, as if there is no published on date, you don't want to see that post at all. I know it's only locally, but I figure it's something worth solving. 
Proposal: remove the draft column. Identify drafts by the fact that they don't have a 'published_on' date in the table to indicate that they are a draft.
These are musings from my discoveries today. Will try to act on them

**Comment by til** [comment]
Makes sense - I suggest to then rename the column to published_at, to
follow the convention "_on" for dates, "_at" for datetimes.

**Comment by berlintam** [comment]
#yolo merged
