### ISSUE TITLE
prevent scroll-zooming on the map (super annoying)

### ISSUE THREAD

**Issue by lislis** [rubycorns/rorganize.it#271]
put ```scrollWheelZoom: false``` to map options

**Comment by sareg0** [comment]
okay peoples. I have researched this, and I cannot figure out how to disable the scroll zoom using the leaflet gem.

I am of the opinion we leave this be. I know it's annoying if a map is taking up the whole page and a really big section, and you're stuck in it and can't get down to the next page section or up because you can't get out of the map, or if you are on a mobile and can't get past map because your fingers just scroll the map. gaaahhhhhhhhhhh!!!!

Okay, so I wanna fix the map to not be scrollable on smaller screens unless you pinch. I will figure it out, but I could just do with some help is what I'm saying in a round about sort of a way.

HAAALLLP!!

**Comment by sareg0** [comment]
Okay, so I agree that having scroll zoom on a map is super annoying, particularly when the maps takes up the whole view port, and you seem to be 'stuck' in it.

However I think that the tile is small enough on the RoRganize.it app, that one will be ok on Desktop, but mobile is particularly problematic; the map does indeed take up the whole view on mobile and if you reach down with your thumb and try to scroll the page up it does it go scrolling off into nowhere.

So for the use case on mobile at the very least I was interested in implementing this.

However, @lislis when I add `scrollWheelZoom: false` to the map options in the 'groups_helper' nothing happens. Am I putting it in the wrong place? 

I faffed about with it for quite some time last night, and couldn't get it to stop scroll zooming.

**Comment by sareg0** [comment]
So after speaking with @lislis and looking at the Gem, we are of the opinion that the scrollWheelZoom property simply isn't in the leaflet-rails gem. Apart from that some pull requests and issues have been sitting for quite some time.

This makes us hesitant to make a pull request.

With this in mind, we thought it might be better to simply just do the map ourselves using JavaScript. 

This would involve implementing the library into the project as a part of the assets of the project, and removing the gem.

We might do this between now and the next Rubycorns, or at the Rubycorns on Tuesday.

**Comment by sareg0** [comment]
I'm closing this puppy up now.
PR #406 has prevented the scrolling with a mouse, and has also replaced the leaflet gem for ruby, with the CDN for the library, and a JavaScript.
BOOM!

**Comment by til** [comment]
Yeah, congrats! :smile:
