### ISSUE TITLE
[Feature] "Currently searching" status

### ISSUE THREAD

**Issue by 1000miles** [rubycorns/rorganize.it#287]
Hello again everyone,

we realized that a lot of people have registered for the Rails Girls App but for a long while nothing happens after the registration. I assume that the first step to contact others is always the hardest for newbies, if they don't know the other people and their demands (searching/not searching).

An option to make it visible that someone is looking for something might help?

If yes, I would like to suggest following:
- provide an option to change a profile status into "currently searching" 
- after "searching"status is activated, provide a checkbox to select: a) project group b) coach c) co-students

Maybe this could be an additional feature to your ticket #115 to filter people by the status "searching"?

Happy to receive your feedback. :)

Best,
Thuy

**Comment by PragTob** [comment]
Note to developers, decide what the best plan of attack is here, be it tags, boolean fields or whateves.

**Comment by lislis** [comment]
I'll give this a shot!

Since we implemented `full`, `mixed_group` and `inactive` as just booleans on groups, I'll do the same for `searching`.

Groups will get 
- `searching coaches`
- `searching students`
- `searching location`. 
People (both Students and Coaches) will get `searching group`

Groups and People should be filterable by these properties. Use case: RG Berlin tweets after a workshop 'These groups are looking for coaches <link>'

**Comment by lislis** [comment]
@sareg0 suggested using a column type jsonb and use a more generic name like `status
`

**Comment by lislis** [comment]
we decided against it ^ so nvm :dancer:

**Comment by lislis** [comment]
Started PR here https://github.com/rubycorns/rorganize.it/pull/508

**Comment by lislis** [comment]
This was shipped with https://github.com/rubycorns/rorganize.it/pull/508 and there is a small blog post https://rorganize.it/posts/all-statuses-on-searching.
Closing this!

On a side note, I'll want to link to https://github.com/rubycorns/rorganize.it/issues/522 where we can improve linking to searching statuses.
