### ISSUE TITLE
image upload is broken on production

### ISSUE THREAD

**Issue by lislis** [rubycorns/rorganize.it#332]
I tried updating our logo on prod, but it didn't work :cry:

**Comment by berlintam** [comment]
this might be fixed by https://github.com/rubycorns/rorganize.it/pull/330 b/c there was some weird redirects going on in the groups controller. Let's check it out once it's been merged & deployed.

**Comment by berlintam** [comment]
update:

After merging the slug branch & running the `set_slugs` rake task, we noticed that a few groups (ours included), did not sucessfully generate slugs upon saving the group. This is because these groups were invalid (checked by doing `Group.find(1).valid?` on the server). Then, by checking the errors (`Group.find(1).errors.full_messages`), we noticed that the email field was missing from the group. This is a required field which was introduced later on after some groups were already created. In our groups controller, we didn't have a redirect back to the edit page & we didn't display errors if something was wrong with the update, so these invalid groups had no way of knowing what was wrong. This is now fixed. So groups can now be updated & are now told if something is wrong. 

As for the image upload thing. Still no idea. It works locally. So..... ya.

**Comment by lislis** [comment]
Not sure if this was mentioned somewhere, but we made the contact info required and I think that also played into the broken upload together with the redirect issue. Anyway it seems to work now (updated rubycorns logo now, yay!) So I'm closing this for now
