### ISSUE TITLE
Geocoding error?

### ISSUE THREAD

**Issue by berlintam** [rubycorns/rorganize.it#361]
This happens when running tests

`Google Geocoding API error: over query limit.`

why? mystery. maybe google will know.

**Comment by til** [comment]
Hm, maybe a test triggers the geocoding API? And when the test is run
many times, e.g. also by Travis, then the test fails?

As a general rule, tests should _never_ do external network calls.
Otherwise the tests depend on external systems and become unreliable.
And unreliable tests are the worst thing ever!

Here's a tool to disallow all network requests from tests - maybe
someone wants to try adding it to our app, and see what happens?
https://github.com/bblimke/webmock

**Comment by PragTob** [comment]
What til said. Although I'd rather use [vcr](https://github.com/vcr/vcr) (which in turn uses webmock) as it already manages recording and replaying the requests.

We might want to look into it further, as it might happen in production and we just don't know about it.. no error reporting :(

**Comment by berlintam** [comment]
LET'S SET UP ERROR REPORTING! (so that we can ignore it... like professionals)

**Comment by PragTob** [comment]
Such fast, many wow... see #363

**Comment by til** [comment]
Agreed, using vcr right away instead of webmock would be cool.

So, this is still a problem, any takers?

**Comment by jasminechao** [comment]
@sareg0 I'm getting the same error when I try to seed. I can't really figure out the solution from this thread...

**Comment by sareg0** [comment]
@jasminechao if all the other tests are running it might be okay to ignore the warnings for now. We could take a look together. I saw them too for a long time, but now when running the specs I don't see them anymore. Perhaps together we could work out what could be causing it still. 

Can you still proceed, or are the warnings a blocker?
