### ISSUE TITLE
Setup error reporting

### ISSUE THREAD

**Issue by PragTob** [rubycorns/rorganize.it#363]
Our system could throw errors all the time and we wouldn't even know... don't know if there's a good free way to do it - @til ?

**Comment by berlintam** [comment]
https://github.com/errbit/errbit

**Comment by PragTob** [comment]
@berlintam we'd still have to have a server where we can run it, no? Maybe it's time to get a DO acc or something.

**Comment by berlintam** [comment]
DO acc?

**Comment by PragTob** [comment]
[Digital Ocean](https://www.digitalocean.com/) - VPS starting at 5$/month

**Comment by til** [comment]
Well ... in other projects, I have used hoptoad, which was later renamed
into airbrake if I remember correctly, then we switched to bugsnag. A
never ending journey it seemed, from one external service to another,
for something that actually doesn't require a complicated external
service at all. Now I'm using this in a couple of projects:
https://github.com/smartinez87/exception_notification and it works very
well - it sends an email to a configured address when an error occurs,
that's it.

**Comment by lislis** [comment]
I think I'd like to finally tackle this issue.
I'd try the `exception_notification` gem and send emails to the mailing list. 
Or would this be too spammy?
Should we set the email address in an env var in the config or somewhere?

**Comment by til** [comment]
> I think I'd like to finally tackle this issue.
> I'd try the exception_notification gem and send emails to the mailing list.
> Or would this be too spammy?

Cool. The exception_notification recently added an option to group
exceptions:

https://github.com/smartinez87/exception_notification#error-grouping

which should prevent getting hundreds of mails if the same error occurs
over and over, which is likely. So we should enable that. Otherwise,
maybe just enable it first, and if it turns out to be too annoying tune
it down again?

> Should we set the email address in an env var in the config or somewhere?

I wouldn't mind hardcoding the address - we already have it somewhere
for the monitoring, right? I assume it should go to roar@rorganize.it,
right?

**Comment by lislis** [comment]
This is done and deployed! And we got our first email :dancer: 
Closing this ticket. Thanks @sareg0

**Comment by til** [comment]
:sparkle: :man_dancing: :100:
