### ISSUE TITLE
Test that documentation is up to date

### ISSUE THREAD

**Issue by sareg0** [rubycorns/rorganize.it#372]
This issue is to be featured as part of a documentation hackday.

It would be great to check if the installation of the app for a newcomer is fast and easy.

**Comment by berlintam** [comment]
@sareg0 can you add the documentation hackday link in here as well?

**Comment by PragTob** [comment]
:+1: please do!

**Comment by sareg0** [comment]
@berlintam I was never able to find a link over the weekend
I don't there were any pull requests thought, but I will still try to find the link

**Comment by robinboening** [comment]
@sareg0: @sonjaheinen and me went to WriteTheDocs in prague. But we did not present the RubyIssues there, which was our intention at first.

We will pick this for the next edition of RubyIssues in two weeks - if its still an issue then :)

**Comment by sareg0** [comment]
@robinboening okay that would be great! You could mark it, 'beginner friendly' even if you like

**Comment by berlintam** [comment]
http://www.writethedocs.org/conf/eu/2015/

**Comment by sareg0** [comment]
awesome thanks @berlintam

**Comment by stratigos** [comment]
@sareg0 Hello, found this issue on RubyIssues :smile: 

I've made PR #394 to include a note about branch pushing permissions in the README.md. Otherwise, all steps to clone, setup, and run site locally produce a working dev environment. No troubles encountered. Obviously I diddnt test the "Deploy to Shelly Cloud" section :wink:.

I've noticed that `config/secrets.yml` is not included in .gitignore. Would you like me to add it to .gitignore? If so, within the scope of this PR, or should I make a separate PR for that?

In addition, running migrations for a new project results in a modified `db/schema.rb` at this time. I could commit the up-to-date file post migrations, but I am not sure what scope/issue in which to include a PR for that.

**Comment by robinboening** [comment]
Happy to see you coming from RubyIssues @stratigos :) :heart:

**Comment by berlintam** [comment]
@stratigos thanks a billion for looking at this! (& sorry for the delay!)

As for adding the secrets to gitignore, I think that @BriocheBerlin managed to solve that problem a week or so ago at rubycorns, so that can be.... ignored... haha! :)

You're right, running migrations modifies the schema. I'm not sure what to do about that. If one has no new migrations, I would say it's just best to throw that away, and this tip can be added to the readme. @PragTob @til what are your thoughts on this?

**Comment by sareg0** [comment]
I made an update to the README in regards to the changes to the schema file. 
@til took care of the config/secrets.yml file not being in the .gitignore folder, so all is well with the world. 
I'll close this up for now, but we might open up a new one again next year to make sure we're keeping an eye on everything being easy to install and get running.
