### ISSUE TITLE
order coaches list better 

### ISSUE THREAD

**Issue by sareg0** [rubycorns/rorganize.it#418]
Currently the coaches list doesn't really have any rhyme or reason to it! It would be nice to order it by something like alphabetical order.

**Comment by BriocheBerlin** [comment]
@til or @PragTob I made this one very unspectacular change to the coaches controller: 
`@coaches = Person.where(workshop_coach: true).order(:first_name, :last_name)`
It does work in general, only this one name "Zlatan" is not doing what it is supposed to!
<img width="329" alt="screen shot 2016-01-19 at 21 50 43" src="https://cloud.githubusercontent.com/assets/6567555/12431822/f368f7c2-bef7-11e5-9e9c-c47efe3cccc6.png">

**Comment by berlintam** [comment]
best bug ever! I love it!

**Comment by sareg0** [comment]
hehhe, oh Zlatan, always being the trickster :)

**Comment by til** [comment]
If Zlatan would be more humble and write himself as "zlatan", then in your example it would work as expected.

A couple of options:
- it's fine like this for now
- order by lower() in the database
- order by downcase in ruby

Since we are loading all the coaches at once anyway because there not thousands of them, I'd tend towards the last option.

**Comment by BriocheBerlin** [comment]
closed by #428
