### ISSUE TITLE
Thumbnails on groups#index have the wrong size

### ISSUE THREAD

**Issue by lislis** [rubycorns/rorganize.it#466]
We render the wrong thumbnail size for group images and then 'scale' them up via css which results in blurry images. No good. We have the appropriate size (as thumbnails on people shows you) so we should use it.

**Comment by veracl** [comment]
I looked into this, but I am not sure what the best way to go about fixing this would be and have some questions. Hopefully someone can give some input :)

I was able to fix the blurriness by changing the line

`= image_tag(group.picture_url(:thumb))`

to

`= image_tag(group.picture_url(:person_profile))`

in app/views/shared/_group_picture.html.haml. This mirrors how the thumbnails on the people index are displayed.

It works, but I think its not the prettiest fix because of the unfitting name. I looked into which versions of uploaded images are currently created by carrierwave:

```
# app/uploaders/picture_uploader.rb
# Create different versions of your uploaded files:
version :thumb do
  process resize_to_fill: [40, 40]
end

version :person_profile do
  process resize_to_fill: [370, 370]
end

version :group_profile do
  process resize_to_fill: [1200, 300, :north]
end
```

and group_profile does exist as well, but as far as I could tell it's currently not actually used anywhere. Maybe it could be removed and person_profile renamed to something more general like profile_picture?
Also, should the index display a scaled down profile picture like it currently does or should we add another thumbnail size (like 100x100) for that?

**Comment by til** [comment]
Thanks for looking into this.

I agree that the naming should be improved - "person_profile" doesn't
really make sense when used for groups. Its better when the name
describes the characteristics of the version, ie. its size, not the
intended usage. "thumb" does that. Maybe add a "medium" or "bigthumb"
version?

How to fix it depends on how much time you want to put into it. Using
:person_profile for the group picture would already be a visible
improvement.

Creating a new medium thumbnail size for both people and groups index
would be a useful additional next step, to avoid unnecessary data
transfer and downscaling. The size seems to be responsive, changing with
the browser width - which is cool, but makes it harder to exactly know
which size is needed. For me it starts with 95x95 and changes to 72x72
when narrowing the browser. I guess 100x100 is reasonable, but maybe
someone with more CSS insights wants to chime in.

Renaming person_profile would be another useful step, but be aware that
probably some kind of migration is needed to rename or recreate the
existing version files. And removing the unused group_profile version:
yes please!

If you really want to put in a lot of time, consider replacing
carrierwave with my personal favourite image processing library ;-),
http://markevans.github.io/dragonfly/ . It needs no pre-processing - you
simply specify the desired size in the link in the view, and the file
will be created when it is first requested. However, I wouldn't know
exactly how to migrate our existing carrierwave images to it. So,
possibly a lot of work.

**Comment by lislis** [comment]
I addressed this in https://github.com/rubycorns/rorganize.it/pull/573

**Comment by lislis** [comment]
this was merged and shipped!
