### ISSUE TITLE
Staging Server for Redesign

### ISSUE THREAD

**Issue by sareg0** [rubycorns/rorganize.it#470]
In doing the redesign, it would be great for @katrin-k to have a place to deploy her changes to, where we could take a quick look, without having to open her branch locally every time.

I propose a staging server, but want to know if this is even feasible with the hosting that we have.

If not this as a solution. @til you mentioned another way; a route like '/redesign' where the new design would live. I felt like it wouldn't be that simple to do, but please let me know if I am mistaken.

If you could all help me with some brainstorming and a solution for Katrin, that would be great!!

**Comment by berlintam** [comment]
maybe it could be like, if you're an admin, you displayed the redesign, and if u're not, you don't? Perhaps that's an easier way to go about doing it.....

**Comment by til** [comment]
I am still in favor of the variant that shows the redesign unobtrusively
within the main app. Either as a /redesign URL with pages underneath it,
or with a URL parameter that can be appended to any existing URL and
causes the design to switch, so that e.g. from
https://rorganize.it/coaches one could switch to the new version by
changing the URL to https://rorganize.it/coaches?redesign=true .

We could also make the switch based on whether the current user is an
admin. But this contains the danger of a disconnect. We, the admins,
always see one version of the site, and the users see another version.
We might even overlook errors in the user version of the site. One would
need to explicitly log out and then look at the page to check. Also the
redesign could then not easily be previewed by non-admins.

A staging server would be another solution. I have the feeling though
that it would require a lot more work to initially set it up and keep it
running, compared to an in-current-app way.

What about the following experiment, that someone could try as first
step: create a redesign.css.scss file next to our current
application.css.scss, and try to change our application.html.erb so that
it includes the redesign.css when the URL contains ?redesign=true, ie.
when `params[:redesign]` is true. If someone wants to try to tackle
that, that would be great, and a first useful step I think. I'll be
happy to answer any questions.
