### ISSUE TITLE
add autostart script to uberspace

### ISSUE THREAD

**Issue by lislis** [rubycorns/rorganize.it#480]
Hey! Sorry for the awkward wording....
The following https://twitter.com/ubernauten/status/774061796533559296

Uberspace rebooted our server because of a RAM upgrade. That terminated our thin server.
All is fine, I restarted it manually, but it would be cool if we had a script that executes thin if the host machine reboots.

**Comment by til** [comment]
Thanks Lisa!

Yes, an automated start on boot would be great, and also a restart in
case it has crashed. The recommended way to do this on Uberspace seems
to be daemontools: https://wiki.uberspace.de/system:daemontools Someone,
please read that page and try to configure a script for our server. If
there are any questions, feel free to ask!

**Comment by BriocheBerlin** [comment]
Dang, it didn't work out.
- So I firstly I guess I put it in the wrong place (because this deploy folder is for use with 'git-deploy' gem. Should I revert maser or how to undo this in the best manner?
- Also when I killed thin (after placing the file in the config folder, the log produced `./run: line 2: exec: /home/ror/html/rorganize.it/config/autostart: cannot execute: Permission denied`. (I followed https://wiki.uberspace.de/system:daemontools "Einen Daemon einrichten", the long version, short one wouldn't do the trick.)

So it didn't work. What am I missing?

**Comment by til** [comment]
Ah yes, I didn't notice the meaning of the deploy folder either. Yes,
that's probably not the best fitting place. I guess a new PR with a new
commit that moves the file to a different place would be an ok way to go
forward. The file doesn't really cause a problem in the meantime when it
is still there.

Permission denied most likely comes from the fact that the file is not
marked as being executable. That's the so-called executable bit of unix
permissions, which is shown by `ls -l`. E.g. this file is not
executable:

$ ls -l README.md 
-rw-r--r-- 1 tils users 4766 Aug 10 18:44 README.md
    16:25:02 ~/rorganize.it (master *)    

but this one is:

$ ls -l bin/rails 
-rwxr-xr-x 1 tils users 145 May  4 22:58 bin/rails

when I try to execute the README (which doesn't make a lot of sense), I
get

$ ./README.md
bash: ./README.md: Permission denied


To make it executable, you can call

chmod +x path/to/the/file

and check with `ls -l` afterwards.

**Comment by til** [comment]
Now where to put this file? It's a bit weird because normally all the
files stay under the project root, but the destiny of this file is to be
put somewhere else, outside of the project root.

Having it as part of our project would only serve as a documentation -
you'd still manually need to copy/symlink it to where it needs to go.
So: feel free to do as you like. One way would be to put it somewhere
under config, or just put it manually on uberspace and not having in git
at all.

Some projects use configuration management tools such as ansible, chef
or puppet for these kinds of things (but I don't think we should start
with this now).

**Comment by til** [comment]
Thanks to @BriocheBerlin, rorganize now runs under daemontools, yay! That means if the ruby server process crashes for whatever reason, it will automatically be restarted.

The service is named `autostart`. You can check its status with `svstat service/autostart`.

daemontools can be a little bit weird in the beginning. For example, I would expect that a restart works with `svc -k service/autostart`, but it doesn't. It doesn't return an error either, but just doesn't do anything. For now, we restart the service `pkill -f thin`. Brutal but effective.

Also the directory of the rails app on the uberspace server changed. It shouldn't be under `html`, but was moved in the home directory now.

**Comment by til** [comment]
Open todo: `~/rorganize.it/config/autostart` currently contains an absolute path to bundler, because the PATH is not set up like it is in the shell. The absolute path contains the ruby version number, so it would probably break if the ruby version number is changed on the server. It would be good to find out how to make this more resilient, e.g. by calling some uberspace-specific setup script to set up the path. Someone (tm) could email uberspace support and ask (they are very friendly and helpful!).
