### ISSUE TITLE
Rethink group editing permissions

### ISSUE THREAD

**Issue by lislis** [rubycorns/rorganize.it#487]
We got a feedback email concerning who has permissions to edit a group.
Here is a short summary (abbreviated original converstion):

```
A: it seems that currently everyone is allowed to edit groups. Is that intended?
B: Currently every member of a group can edit that group.
A: I would prefer if only the owners of the group could do that
B: How would you define the owners?
A: The creator of the group should be the owner. But it then would be probably necessary to give ownership also to someone else.
```

Other opinions?

**Comment by sareg0** [comment]
I am in favor of having the creator be the 'administrator' of a group, and therefore having the permission to edit the group. 
The admin should be able to appoint other admins. 
They cannot leave the admin role of a group before they have appointed at least one other admin to the group.

**Comment by berlintam** [comment]
So, my 2 cents:
* We used to have rolify, but I removed it because it was a bit overloaded for what we needed for Rorganize. Technically we only needed an admin role (that is us) at the time. 

* I do enjoy rolify, it's quite simple to implement & use & to give ppl roles & take them away. I *think* you can define your own roles (admin, editor, whatever etc...), and then say what they can do. If we decide to use rolify however, we would have to map all our current admin users to have an admin role. This isn't the end of the world, it's just something we gotta take into consideration. 
* cancancan also seems like a good choice. I've never used it, but it's popular. It might also fit better to our current solution seeing as we have an `.admin` boolean on the user. I don't think we'd have to map all our current admins to the cancancan solution. Instead we can just define what admins can do (everything), and also add a `group_owner` flag to the user & define what they can do too (edit/manage their group, create other owners)
* pundit I have no idea. I've never heard of it/used it. But it says it's 'minimal' which is better than rolify & cancancan!

**Comment by berlintam** [comment]
OH, and if we use rolify again, we need to be careful we don't run into this problem again https://rorganize.it/posts/were-you-ever-a-railsgirlsapp-admin?redesign=true

**Comment by lislis** [comment]
I've thought about this some more and I think adding group ownership to the Person/ User is the wrong approach. 
Instead we could roll with a boolean flag on the Membership. You can have multiple Memberships, but your Membership to one group can be different from another.

This would mean implementing the following:
- add an owner column to the Membership model
- automatically make the user who creates a group and owner (aka in the membership set owner to true)
- have an owner interface on groups that only the group owner (and overall admins?) can access. There they can make other group members (Membership required!) owners

Wdyt?

**Comment by lislis** [comment]
We just shipped group admins! Read about it here https://rorganize.it/posts/introducing-group-admins

It addresses this issue but we should also work on approving memberships, too. But that's a different thing...  (https://github.com/rubycorns/rorganize.it/issues/449)

Closing this for now

**Comment by til** [comment]
Hooooooooooray! ;-)

**Comment by vsmart** [comment]
OMG Awesome! 

![yes](https://media.giphy.com/media/l1J3AQyDNsTviUFpe/giphy.gif)
