### ISSUE TITLE
Setup Monitoring!

### ISSUE THREAD

**Issue by sareg0** [rubycorns/rorganize.it#489]
Last week, rorganize.it had some downtime that a number of us probably didn't know about. 

Lisa alerted us, but I had trouble ssh-in/logging into uberspace, and in the end Til restarted the app/server to get it running again.

We need to set up monitoring so that we can be alerted of downtime via email, and also we need to go over our process for fixing such problems so we can spread the knowledge a bit.

**Comment by PragTob** [comment]
thank you for bringing this up @sareg0 !

1. document deployment/restart process thoroughly
2. get app monitoring up - pingdom is fairly popular - they just do a request and see if you're still up. [newrelic](http://newrelic.com/) has a free tier with only one day data retention - not sure how much uptime monitoring they go. We could also look into bug monitoring like bugsnag, honeybadger or other services... not sure about the free availability of all of them
3. make it so that 1. is just one command to fire off so that there actually isn't much documentation - back at the time we wanted to set it up with capistrano through [capistrano-ueberspace](https://github.com/tessi/capistrano-uberspace) which would be great as capistrano is the standard ruby tool chain for this.

quick input from a laptop while listening to a talk I really want to listen to :)

**Comment by sareg0** [comment]
1. yes! Documentation = good. We do have a decent run down of the deployment process so far, so think that's ok. Is it useful to document restart procedures to the general public when they should not be the ones restarting things i.e. it's just 'internal' maintainer info if you know what I mean.
2. Would it be realistic to setup some cronjobs to run at intervals on the server. Scripts that monitor the processes on the server and send emails would be great. I am only in favor of such a solution because some of the tools out there are so big, and our needs are very simple: app is down? get an email. restart manually by whoever can ssh in.

In regards to the bug monitoring that seems like a separate issue, also... I'm a big fan of breaking things up into small chunks.

3. okay. I think we should perhaps discuss an update to the deployment process in a new issue, since it is sort of separate, and might get lost here.

**Comment by lislis** [comment]
So, here is our home-made ping:
https://github.com/rubycorns/rorganize.it/pull/490

We now have a cronjob running every 5 minutes that curls rorganize.it. If the statuscode is anything but 200 it will send an email to our mailing list

**Comment by til** [comment]
Regarding 3.:

Deploy already _is_ a single command to fire off, and it's documented in
the README in the Deploy section, it's: "git push production master"

There is a git post-receive hook set up on the production repository
that does the assets recompile, database migrations and server restart
automatically, using git-deploy (https://github.com/mislav/git-deploy).
What could capistrano-uberspace improve here?

As for the restart - the recommended way on Uberspace to run a daemon is
according to their documentation daemontools, so Brigitte set that up
some time ago. If we'd switch to capistrano-uberspace then we would
continue to use that mechanism for restarting the app I suppose, so any
problems that we might have had with it previously would remain the
same.
