### ISSUE TITLE
Add FAQ page

### ISSUE THREAD

**Issue by lislis** [rubycorns/rorganize.it#503]
RoRganize is gaining some traction. Who knew?!
It might be beneficial to add a faq page to clarify things:

- What is RoRganize.it?
- Do you offer courses? How can I subscribe?
- How can I join a group?
- How do I know a group is still meeting/ active?
- What happens at a study group?

**Comment by berlintam** [comment]
we already have a welcome page, maybe this information can just be added to that?

However, you get redirected to the welcome page after you sign up, I guess an FAQ page is also important for ppl who haven't signed up yet. 

We have an about page, what if we add that information there? We can rename the page 'About/FAQ' or perhaps slightly redesign it....

wdyt?

**Comment by lislis** [comment]
I think About/FAQ makes most sense 💯

**Comment by dondonz** [comment]
Hello folks - has someone started working on this? I'm happy to take this one on

**Comment by til** [comment]
Not that I know of - probably not, otherwise there would be at least a
WIP pull request. Feel free to get it started!

I'm also in favour of merging the FAQ into the existing About page, to
avoid having too many small different pages with a similar purpose.
Probably the information on the current about page could be restructured
into a few FAQ questions and then we could rename the whole page to just
"FAQ" - but that's just a thought, do as you think is best.

**Comment by lislis** [comment]
@dondonz Are you still up for this one? Can I assign this ticket to you?
I can put together the content if you like and paste it here

**Comment by dondonz** [comment]
@lislis Hello! Yes I'd like to take this one. Sure that sounds great.

**Comment by dondonz** [comment]
@lislis Hello, I'm sorry, it's been an incredibly busy time for me, and being ill too :( 

If anyone else would like to take this ticket, do jump on!

**Comment by lislis** [comment]
Started a PR #559

**Comment by lislis** [comment]
shipped it!
