### ISSUE TITLE
try out Action Cable

### ISSUE THREAD

**Issue by berlintam** [rubycorns/rorganize.it#509]
Rails 5 comes with Action Cable, which I'd totally like to try out. I followed a tutorial & built a chat app, but I'd like to do something action-cable-y with an existing project like.... rorganize for example :)

http://edgeguides.rubyonrails.org/action_cable_overview.html

@lislis you had a PR at some point with notifications, right? Is that still ongoing? Maybe that's a good place to incorporate this? Or.... maybe we can have a chat within the groups? Or... something else? Maybe I can just build a chat into the admin area for... reasons.... Or of course something non-chat related would also be possible :)

Anyone have any cool ideas?

**Comment by lislis** [comment]
@berlintam I closed the notifications PR as it was too much overhead and my approach didn't really cover the foundational work for applying for groups...

Instead of chat, what I could imagine as a real time feature would be related to https://github.com/rubycorns/rorganize.it/issues/457 
So there would be meetings for groups and you can check into an meeting and then you can see who attends the meeting in real time? WDYT? and then the meeting group can chat as well?

**Comment by PragTob** [comment]
hmmm. A Chat certainly is the 101 use case for this sort of thing, I don't think checking in needs this (as it just says "HEY I'm here" or something if I understood correctly). 

I'm just a bit worried that it might be too much for our current hosting, but maybe I'm too performance minded/scared. E.g. Ruby really isn't  a great platform for what ActioCable does - plus iirc it was recommended to start the ActionCable server standalone which would almost double our app memory usage (or so I guess).

Shouldn't matter too much, as we don't have millions of people accessing rorganize.it just some thoughts. A chat would be kind of cool, as the IRC seems kinda dead :|

**Comment by berlintam** [comment]
Sorry Tobz, I don't follow. Action Cable is included in Rails 5 from what I understood, so it wouldn't require anything extra on our part (just using it), oder?

**Comment by PragTob** [comment]
Hey hey hey!

So yes, it doesn't require an extra installation or something but we still need to run it. But afaik [running it standalone](http://edgeguides.rubyonrails.org/action_cable_overview.html#running-standalone-cable-servers) is more recommended. And always of course some configuration.

Usually the standalone is more used to achieve parallelism, as you know ruby has the Global Interpreter Lock (GIL) and so no 2 pieces of ruby code can truly execute at the same time. So that the load of the channels/ActionCable does not affect the web server/HTTP handling too much. That isn't really that important for us though, as we only have one core on our production server I believe.

Because basically, with normal HTTP Ruby we get a request, compute the response on the server, send it and then we're free to deal with other stuff.

With ActionCable/channels whatever they're called it's a bit different. That's a full duplex connection where information flows in both directions and potentially there's more going on - during which the http requests can not be handled.

For our scale it's probably not a problem, I'm just very cautious when it comes to these things and not convinced at all of the performance of ActionCable. E.g. [here is a comparison](https://hashrocket.com/blog/posts/websocket-shootout)  and here a [more direct head to head](https://dockyard.com/blog/2016/08/09/phoenix-channels-vs-rails-action-cable).

Again, probably not that important for us and I'm just over cautious as long as people don't start using it A LOT and at the same time but yeah, not a big ActionCable fan :) It's a complex topic, we could meet up and talk in person as it's a lot =)

**Comment by lislis** [comment]
Hey people! Is it ok if I close this ticket? From what I read and understand we don't have a good use case for Acton Cable?
I'll also open a ticket to upgrade to Rails 5 anyway

**Comment by PragTob** [comment]
fine by me :angel:
