### ISSUE TITLE
Add form fields to manually update github handle

### ISSUE THREAD

**Issue by lislis** [rubycorns/rorganize.it#602]
Via c43bef8bdcce98b23694e7c308b8a56eb2d5c4bd we now have github handles on profiles.
The nice thing is that is works automatically when you sign in via GitHub but unfortunately not when your account is already associated with GH (older accounts) or you signed up without GH but would still like to show you handle in your profile.
I guess we could add regular form fields that allow editing/updating the GH handle manually.

**Comment by Seunadex** [comment]
@lislis i can work on this, but i will like to point out that when manually updating the github handle, are we going to trust the user to input their correct handle because if they don't enter their own handle and if the handle is available onClicking of the link takes them to a wrong page or if the handle  does not exist on github it returns `404`, hope you get my point?

**Comment by lislis** [comment]
@Seunadex I get your point. But we're also trusting people to enter their correct twitter handle which could result in the same problematic outcomes.
I think in our case it's okay to accept the user's input on these fields since we assume that they want to have their correct info on their profile. If they put in the wrong info by accident they will notice it themselves and if they try to impersonate someone else on purpose then, well, it's just a link I guess?

**Comment by lislis** [comment]
Closed by #604

**Comment by Seunadex** [comment]
@lislis, Yeah, so i've raised a PR for that
